version: '3'
services:
  db:
    image: postgres
    container_name: pgsql
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      dailynet:
        ipv4_address: 172.16.25.2

  django:
    build:
      context: .
    environment:
      - DJANGO_DEBUG=True
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on: 
      - db
    container_name: dailypicture
    networks:
      dailynet:
        ipv4_address: 172.16.25.3
networks:
  dailynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.25.0/24
